FROM registry.fedoraproject.org/fedora:latest

LABEL org.opencontainers.image.description "Send earnings reports to the ThetaGang Discord"
LABEL org.opencontainers.image.authors "Major Hayden <major@mhtx.net>"
LABEL org.opencontainers.image.url "https://github.com/major/thetagang-scripts"

RUN mkdir /app
COPY earnings_reports.py requirements.txt /app
RUN dnf -y install python3-pip python3-yfinance python3-wheel && dnf clean all
RUN pip3 install -r /app/requirements.txt
RUN chmod +x /app/earnings_reports.py
CMD ["/app/earnings_reports.py"]
